# Generated by Django 3.1.5 on 2021-01-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='api.event'),
        ),
    ]
